// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCinema;

#nullable disable

namespace WebCinema.Migrations
{
    [DbContext(typeof(WebCinemaDBContext))]
    [Migration("20250313081019_newSeats3")]
    partial class newSeats3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCinema.Models.Actors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Timothee",
                            LastName = "Chalamet"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Rebecca",
                            LastName = "Ferguson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Oscar",
                            LastName = "Isaac"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Russel",
                            LastName = "Crowe"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Joaquin",
                            LastName = "Phoenix"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.BookedSeats", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "SeatsId");

                    b.HasIndex("SeatsId");

                    b.ToTable("BookedSeats");
                });

            modelBuilder.Entity("WebCinema.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowTimesId")
                        .HasColumnType("int");

                    b.Property<int>("TicketQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowTimesId");

                    b.HasIndex("UsersId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebCinema.Models.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sarajevo"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "France"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Directors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ridley",
                            LastName = "Scott"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Denis",
                            LastName = "Villeneuve"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Genres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Historical"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Halls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HallType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TheatersID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheatersID");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 60,
                            HallName = "Hall1",
                            HallType = "Medium",
                            TheatersID = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 90,
                            HallName = "Hall2",
                            HallType = "Big",
                            TheatersID = 1
                        });
                });

            modelBuilder.Entity("WebCinema.Models.MoviePoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PosterImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviePoster");
                });

            modelBuilder.Entity("WebCinema.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WebCinema.Models.MoviesActors", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MoviesActors");
                });

            modelBuilder.Entity("WebCinema.Models.MoviesGenres", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MoviesGenres");
                });

            modelBuilder.Entity("WebCinema.Models.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WebCinema.Models.Ratings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.HasIndex("MoviesId", "UsersId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WebCinema.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Moderator"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Seats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallsId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallsId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallsId = 1,
                            SeatNumber = 1,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            HallsId = 1,
                            SeatNumber = 2,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            HallsId = 1,
                            SeatNumber = 3,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 4,
                            HallsId = 1,
                            SeatNumber = 4,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 5,
                            HallsId = 1,
                            SeatNumber = 5,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 6,
                            HallsId = 1,
                            SeatNumber = 6,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 7,
                            HallsId = 1,
                            SeatNumber = 7,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 8,
                            HallsId = 1,
                            SeatNumber = 8,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 9,
                            HallsId = 1,
                            SeatNumber = 9,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 10,
                            HallsId = 1,
                            SeatNumber = 10,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 11,
                            HallsId = 1,
                            SeatNumber = 11,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 12,
                            HallsId = 1,
                            SeatNumber = 12,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 13,
                            HallsId = 1,
                            SeatNumber = 13,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 14,
                            HallsId = 1,
                            SeatNumber = 14,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 15,
                            HallsId = 1,
                            SeatNumber = 15,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 16,
                            HallsId = 1,
                            SeatNumber = 16,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 17,
                            HallsId = 1,
                            SeatNumber = 17,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 18,
                            HallsId = 1,
                            SeatNumber = 18,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 19,
                            HallsId = 1,
                            SeatNumber = 19,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 20,
                            HallsId = 1,
                            SeatNumber = 20,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 21,
                            HallsId = 1,
                            SeatNumber = 21,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 22,
                            HallsId = 1,
                            SeatNumber = 22,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 23,
                            HallsId = 1,
                            SeatNumber = 23,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 24,
                            HallsId = 1,
                            SeatNumber = 24,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 25,
                            HallsId = 1,
                            SeatNumber = 25,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 26,
                            HallsId = 1,
                            SeatNumber = 26,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 27,
                            HallsId = 1,
                            SeatNumber = 27,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 28,
                            HallsId = 1,
                            SeatNumber = 28,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 29,
                            HallsId = 1,
                            SeatNumber = 29,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 30,
                            HallsId = 1,
                            SeatNumber = 30,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 31,
                            HallsId = 1,
                            SeatNumber = 31,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 32,
                            HallsId = 1,
                            SeatNumber = 32,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 33,
                            HallsId = 1,
                            SeatNumber = 33,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 34,
                            HallsId = 1,
                            SeatNumber = 34,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 35,
                            HallsId = 1,
                            SeatNumber = 35,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 36,
                            HallsId = 1,
                            SeatNumber = 36,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 37,
                            HallsId = 1,
                            SeatNumber = 37,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 38,
                            HallsId = 1,
                            SeatNumber = 38,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 39,
                            HallsId = 1,
                            SeatNumber = 39,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 40,
                            HallsId = 1,
                            SeatNumber = 40,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 41,
                            HallsId = 1,
                            SeatNumber = 41,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 42,
                            HallsId = 1,
                            SeatNumber = 42,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 43,
                            HallsId = 1,
                            SeatNumber = 43,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 44,
                            HallsId = 1,
                            SeatNumber = 44,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 45,
                            HallsId = 1,
                            SeatNumber = 45,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 46,
                            HallsId = 1,
                            SeatNumber = 46,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 47,
                            HallsId = 1,
                            SeatNumber = 47,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 48,
                            HallsId = 1,
                            SeatNumber = 48,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 49,
                            HallsId = 1,
                            SeatNumber = 49,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 50,
                            HallsId = 1,
                            SeatNumber = 50,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 51,
                            HallsId = 1,
                            SeatNumber = 51,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 52,
                            HallsId = 1,
                            SeatNumber = 52,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 53,
                            HallsId = 1,
                            SeatNumber = 53,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 54,
                            HallsId = 1,
                            SeatNumber = 54,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 55,
                            HallsId = 1,
                            SeatNumber = 55,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 56,
                            HallsId = 1,
                            SeatNumber = 56,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 57,
                            HallsId = 1,
                            SeatNumber = 57,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 58,
                            HallsId = 1,
                            SeatNumber = 58,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 59,
                            HallsId = 1,
                            SeatNumber = 59,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 60,
                            HallsId = 1,
                            SeatNumber = 60,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 61,
                            HallsId = 2,
                            SeatNumber = 1,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 62,
                            HallsId = 2,
                            SeatNumber = 2,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 63,
                            HallsId = 2,
                            SeatNumber = 3,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 64,
                            HallsId = 2,
                            SeatNumber = 4,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 65,
                            HallsId = 2,
                            SeatNumber = 5,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 66,
                            HallsId = 2,
                            SeatNumber = 6,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 67,
                            HallsId = 2,
                            SeatNumber = 7,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 68,
                            HallsId = 2,
                            SeatNumber = 8,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 69,
                            HallsId = 2,
                            SeatNumber = 9,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 70,
                            HallsId = 2,
                            SeatNumber = 10,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 71,
                            HallsId = 2,
                            SeatNumber = 11,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 72,
                            HallsId = 2,
                            SeatNumber = 12,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 73,
                            HallsId = 2,
                            SeatNumber = 13,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 74,
                            HallsId = 2,
                            SeatNumber = 14,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 75,
                            HallsId = 2,
                            SeatNumber = 15,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 76,
                            HallsId = 2,
                            SeatNumber = 16,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 77,
                            HallsId = 2,
                            SeatNumber = 17,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 78,
                            HallsId = 2,
                            SeatNumber = 18,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 79,
                            HallsId = 2,
                            SeatNumber = 19,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 80,
                            HallsId = 2,
                            SeatNumber = 20,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 81,
                            HallsId = 2,
                            SeatNumber = 21,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 82,
                            HallsId = 2,
                            SeatNumber = 22,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 83,
                            HallsId = 2,
                            SeatNumber = 23,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 84,
                            HallsId = 2,
                            SeatNumber = 24,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 85,
                            HallsId = 2,
                            SeatNumber = 25,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 86,
                            HallsId = 2,
                            SeatNumber = 26,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 87,
                            HallsId = 2,
                            SeatNumber = 27,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 88,
                            HallsId = 2,
                            SeatNumber = 28,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 89,
                            HallsId = 2,
                            SeatNumber = 29,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 90,
                            HallsId = 2,
                            SeatNumber = 30,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 91,
                            HallsId = 2,
                            SeatNumber = 31,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 92,
                            HallsId = 2,
                            SeatNumber = 32,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 93,
                            HallsId = 2,
                            SeatNumber = 33,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 94,
                            HallsId = 2,
                            SeatNumber = 34,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 95,
                            HallsId = 2,
                            SeatNumber = 35,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 96,
                            HallsId = 2,
                            SeatNumber = 36,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 97,
                            HallsId = 2,
                            SeatNumber = 37,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 98,
                            HallsId = 2,
                            SeatNumber = 38,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 99,
                            HallsId = 2,
                            SeatNumber = 39,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 100,
                            HallsId = 2,
                            SeatNumber = 40,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 101,
                            HallsId = 2,
                            SeatNumber = 41,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 102,
                            HallsId = 2,
                            SeatNumber = 42,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 103,
                            HallsId = 2,
                            SeatNumber = 43,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 104,
                            HallsId = 2,
                            SeatNumber = 44,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 105,
                            HallsId = 2,
                            SeatNumber = 45,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 106,
                            HallsId = 2,
                            SeatNumber = 46,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 107,
                            HallsId = 2,
                            SeatNumber = 47,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 108,
                            HallsId = 2,
                            SeatNumber = 48,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 109,
                            HallsId = 2,
                            SeatNumber = 49,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 110,
                            HallsId = 2,
                            SeatNumber = 50,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 111,
                            HallsId = 2,
                            SeatNumber = 51,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 112,
                            HallsId = 2,
                            SeatNumber = 52,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 113,
                            HallsId = 2,
                            SeatNumber = 53,
                            SeatType = "Love"
                        },
                        new
                        {
                            Id = 114,
                            HallsId = 2,
                            SeatNumber = 54,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 115,
                            HallsId = 2,
                            SeatNumber = 55,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 116,
                            HallsId = 2,
                            SeatNumber = 56,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 117,
                            HallsId = 2,
                            SeatNumber = 57,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 118,
                            HallsId = 2,
                            SeatNumber = 58,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 119,
                            HallsId = 2,
                            SeatNumber = 59,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 120,
                            HallsId = 2,
                            SeatNumber = 60,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 121,
                            HallsId = 2,
                            SeatNumber = 61,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 122,
                            HallsId = 2,
                            SeatNumber = 62,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 123,
                            HallsId = 2,
                            SeatNumber = 63,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 124,
                            HallsId = 2,
                            SeatNumber = 64,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 125,
                            HallsId = 2,
                            SeatNumber = 65,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 126,
                            HallsId = 2,
                            SeatNumber = 66,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 127,
                            HallsId = 2,
                            SeatNumber = 67,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 128,
                            HallsId = 2,
                            SeatNumber = 68,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 129,
                            HallsId = 2,
                            SeatNumber = 69,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 130,
                            HallsId = 2,
                            SeatNumber = 70,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 131,
                            HallsId = 2,
                            SeatNumber = 71,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 132,
                            HallsId = 2,
                            SeatNumber = 72,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 133,
                            HallsId = 2,
                            SeatNumber = 73,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 134,
                            HallsId = 2,
                            SeatNumber = 74,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 135,
                            HallsId = 2,
                            SeatNumber = 75,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 136,
                            HallsId = 2,
                            SeatNumber = 76,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 137,
                            HallsId = 2,
                            SeatNumber = 77,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 138,
                            HallsId = 2,
                            SeatNumber = 78,
                            SeatType = "Accessible"
                        },
                        new
                        {
                            Id = 139,
                            HallsId = 2,
                            SeatNumber = 79,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 140,
                            HallsId = 2,
                            SeatNumber = 80,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 141,
                            HallsId = 2,
                            SeatNumber = 81,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 142,
                            HallsId = 2,
                            SeatNumber = 82,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 143,
                            HallsId = 2,
                            SeatNumber = 83,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 144,
                            HallsId = 2,
                            SeatNumber = 84,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 145,
                            HallsId = 2,
                            SeatNumber = 85,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 146,
                            HallsId = 2,
                            SeatNumber = 86,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 147,
                            HallsId = 2,
                            SeatNumber = 87,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 148,
                            HallsId = 2,
                            SeatNumber = 88,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 149,
                            HallsId = 2,
                            SeatNumber = 89,
                            SeatType = "Regular"
                        },
                        new
                        {
                            Id = 150,
                            HallsId = 2,
                            SeatNumber = 90,
                            SeatType = "Regular"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.ShowTimes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallsId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ShowTimes");
                });

            modelBuilder.Entity("WebCinema.Models.Theaters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Adress1",
                            CityId = 1,
                            Name = "Teatar1",
                            PhoneNumber = "061 467 946",
                            PostalCode = "88000"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Adress2",
                            CityId = 1,
                            Name = "Teatar2",
                            PhoneNumber = "061 675 875",
                            PostalCode = "88000"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Adress3",
                            CityId = 2,
                            Name = "Teatar3",
                            PhoneNumber = "061 864 079",
                            PostalCode = "71000"
                        });
                });

            modelBuilder.Entity("WebCinema.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RolesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebCinema.Models.UsersImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageByteArray")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersImages");
                });

            modelBuilder.Entity("WebCinema.Models.BookedSeats", b =>
                {
                    b.HasOne("WebCinema.Models.Bookings", "Bookings")
                        .WithMany("BookedSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Seats", "Seats")
                        .WithMany("BookedSeats")
                        .HasForeignKey("SeatsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("WebCinema.Models.Bookings", b =>
                {
                    b.HasOne("WebCinema.Models.ShowTimes", "ShowTimes")
                        .WithMany()
                        .HasForeignKey("ShowTimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShowTimes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebCinema.Models.Halls", b =>
                {
                    b.HasOne("WebCinema.Models.Theaters", "Theater")
                        .WithMany()
                        .HasForeignKey("TheatersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("WebCinema.Models.MoviePoster", b =>
                {
                    b.HasOne("WebCinema.Models.Movies", "Movies")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebCinema.Models.Movies", b =>
                {
                    b.HasOne("WebCinema.Models.Countries", "Country")
                        .WithMany("Movie")
                        .HasForeignKey("CountryId");

                    b.HasOne("WebCinema.Models.Directors", "Director")
                        .WithMany("Movie")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("WebCinema.Models.MoviesActors", b =>
                {
                    b.HasOne("WebCinema.Models.Actors", "Actor")
                        .WithMany("MoviesActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Movies", "Movie")
                        .WithMany("MoviesActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebCinema.Models.MoviesGenres", b =>
                {
                    b.HasOne("WebCinema.Models.Genres", "Genre")
                        .WithMany("MoviesGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Movies", "Movie")
                        .WithMany("MoviesGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebCinema.Models.Payments", b =>
                {
                    b.HasOne("WebCinema.Models.Bookings", "Bookings")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("WebCinema.Models.Ratings", b =>
                {
                    b.HasOne("WebCinema.Models.Movies", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebCinema.Models.Seats", b =>
                {
                    b.HasOne("WebCinema.Models.Halls", "Hall")
                        .WithMany()
                        .HasForeignKey("HallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("WebCinema.Models.ShowTimes", b =>
                {
                    b.HasOne("WebCinema.Models.Halls", "Halls")
                        .WithMany()
                        .HasForeignKey("HallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Movies", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halls");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebCinema.Models.Theaters", b =>
                {
                    b.HasOne("WebCinema.Models.Cities", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WebCinema.Models.Users", b =>
                {
                    b.HasOne("WebCinema.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCinema.Models.Roles", null)
                        .WithMany("Users")
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WebCinema.Models.UsersImage", b =>
                {
                    b.HasOne("WebCinema.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebCinema.Models.Actors", b =>
                {
                    b.Navigation("MoviesActors");
                });

            modelBuilder.Entity("WebCinema.Models.Bookings", b =>
                {
                    b.Navigation("BookedSeats");
                });

            modelBuilder.Entity("WebCinema.Models.Countries", b =>
                {
                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebCinema.Models.Directors", b =>
                {
                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebCinema.Models.Genres", b =>
                {
                    b.Navigation("MoviesGenres");
                });

            modelBuilder.Entity("WebCinema.Models.Movies", b =>
                {
                    b.Navigation("MoviesActors");

                    b.Navigation("MoviesGenres");
                });

            modelBuilder.Entity("WebCinema.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebCinema.Models.Seats", b =>
                {
                    b.Navigation("BookedSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
